hadd hadd_00.root job_00*/outputHist_ttbar.root
hadd hadd_01.root job_01*/outputHist_ttbar.root
hadd hadd_02.root job_02*/outputHist_ttbar.root
hadd hadd_03.root job_03*/outputHist_ttbar.root
hadd hadd_04.root job_04*/outputHist_ttbar.root
hadd hadd_05.root job_05*/outputHist_ttbar.root
hadd hadd_06.root job_06*/outputHist_ttbar.root
hadd hadd_07.root job_07*/outputHist_ttbar.root
hadd hadd_08.root job_08*/outputHist_ttbar.root
hadd hadd_09.root job_09*/outputHist_ttbar.root
hadd hadd_10.root job_10*/outputHist_ttbar.root
hadd hadd_11.root job_11*/outputHist_ttbar.root
hadd hadd_12.root job_12*/outputHist_ttbar.root
hadd hadd_13.root job_13*/outputHist_ttbar.root
hadd hadd_14.root job_14*/outputHist_ttbar.root
hadd hadd_15.root job_15*/outputHist_ttbar.root
hadd hadd_16.root job_16*/outputHist_ttbar.root
hadd hadd_17.root job_17*/outputHist_ttbar.root
hadd hadd_18.root job_18*/outputHist_ttbar.root
hadd hadd_19.root job_19*/outputHist_ttbar.root
hadd hadd_20.root job_20*/outputHist_ttbar.root
hadd hadd_21.root job_21*/outputHist_ttbar.root
hadd hadd_22.root job_22*/outputHist_ttbar.root
hadd hadd_23.root job_23*/outputHist_ttbar.root
hadd hadd_24.root job_24*/outputHist_ttbar.root
hadd hadd_25.root job_25*/outputHist_ttbar.root
hadd hadd_26.root job_26*/outputHist_ttbar.root
hadd hadd_27.root job_27*/outputHist_ttbar.root
hadd hadd_28.root job_28*/outputHist_ttbar.root
hadd hadd_29.root job_29*/outputHist_ttbar.root
hadd hadd_30.root job_30*/outputHist_ttbar.root
hadd hadd_31.root job_31*/outputHist_ttbar.root
hadd hadd_32.root job_32*/outputHist_ttbar.root
hadd hadd_33.root job_33*/outputHist_ttbar.root
hadd hadd_34.root job_34*/outputHist_ttbar.root
hadd hadd_35.root job_35*/outputHist_ttbar.root
hadd hadd_36.root job_36*/outputHist_ttbar.root
hadd hadd_37.root job_37*/outputHist_ttbar.root
hadd hadd_38.root job_38*/outputHist_ttbar.root
hadd hadd_39.root job_39*/outputHist_ttbar.root
hadd hadd_40.root job_40*/outputHist_ttbar.root
hadd hadd_41.root job_41*/outputHist_ttbar.root
hadd hadd_42.root job_42*/outputHist_ttbar.root
hadd hadd_43.root job_43*/outputHist_ttbar.root
hadd hadd_44.root job_44*/outputHist_ttbar.root
hadd hadd_45.root job_45*/outputHist_ttbar.root
hadd hadd_46.root job_46*/outputHist_ttbar.root
hadd hadd_47.root job_47*/outputHist_ttbar.root
hadd hadd_48.root job_48*/outputHist_ttbar.root
hadd hadd_49.root job_49*/outputHist_ttbar.root
hadd hadd_50.root job_50*/outputHist_ttbar.root
hadd hadd_51.root job_51*/outputHist_ttbar.root
hadd hadd_52.root job_52*/outputHist_ttbar.root
hadd hadd_53.root job_53*/outputHist_ttbar.root
hadd hadd_54.root job_54*/outputHist_ttbar.root
hadd hadd_55.root job_55*/outputHist_ttbar.root
hadd hadd_56.root job_56*/outputHist_ttbar.root
hadd hadd_57.root job_57*/outputHist_ttbar.root
hadd hadd_58.root job_58*/outputHist_ttbar.root
hadd hadd_59.root job_59*/outputHist_ttbar.root
hadd hadd_60.root job_60*/outputHist_ttbar.root
hadd hadd_61.root job_61*/outputHist_ttbar.root
hadd hadd_62.root job_62*/outputHist_ttbar.root
hadd hadd_63.root job_63*/outputHist_ttbar.root
hadd hadd_64.root job_64*/outputHist_ttbar.root
hadd hadd_65.root job_65*/outputHist_ttbar.root
hadd hadd_66.root job_66*/outputHist_ttbar.root
hadd hadd_67.root job_67*/outputHist_ttbar.root
hadd hadd_68.root job_68*/outputHist_ttbar.root
hadd hadd_69.root job_69*/outputHist_ttbar.root
hadd hadd_70.root job_70*/outputHist_ttbar.root
hadd hadd_71.root job_71*/outputHist_ttbar.root
hadd hadd_72.root job_72*/outputHist_ttbar.root
hadd hadd_73.root job_73*/outputHist_ttbar.root
hadd hadd_74.root job_74*/outputHist_ttbar.root
hadd hadd_75.root job_75*/outputHist_ttbar.root
hadd hadd_76.root job_76*/outputHist_ttbar.root
hadd hadd_77.root job_77*/outputHist_ttbar.root
hadd hadd_78.root job_78*/outputHist_ttbar.root
hadd hadd_79.root job_79*/outputHist_ttbar.root
hadd hadd_80.root job_80*/outputHist_ttbar.root
hadd hadd_81.root job_81*/outputHist_ttbar.root
hadd hadd_82.root job_82*/outputHist_ttbar.root
hadd hadd_83.root job_83*/outputHist_ttbar.root
hadd hadd_84.root job_84*/outputHist_ttbar.root
hadd hadd_85.root job_85*/outputHist_ttbar.root
hadd hadd_86.root job_86*/outputHist_ttbar.root
hadd hadd_87.root job_87*/outputHist_ttbar.root
hadd hadd_88.root job_88*/outputHist_ttbar.root
hadd hadd_89.root job_89*/outputHist_ttbar.root
hadd hadd_90.root job_90*/outputHist_ttbar.root
hadd hadd_91.root job_91*/outputHist_ttbar.root
hadd hadd_92.root job_92*/outputHist_ttbar.root
hadd hadd_93.root job_93*/outputHist_ttbar.root
hadd hadd_94.root job_94*/outputHist_ttbar.root
hadd hadd_95.root job_95*/outputHist_ttbar.root
hadd hadd_96.root job_96*/outputHist_ttbar.root
hadd hadd_97.root job_97*/outputHist_ttbar.root
hadd hadd_98.root job_98*/outputHist_ttbar.root
hadd hadd_99.root job_99*/outputHist_ttbar.root
hadd outputHist_ttbar.root hadd_*.root
rm hadd_*.root
